version: '3'

services:
  sftpgo:
    image: ghcr.io/drakkan/sftpgo:v2.2.2
    ports:
      - "8080:8080"
    environment:
      SFTPGO_HTTPD__BINDINGS__0__PORT: 8080
      SFTPGO_HTTPD__BINDINGS__0__ADDRESS: 0.0.0.0
      SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN: "true"
      SFTPGO_DEFAULT_ADMIN_USERNAME: admin
      SFTPGO_DEFAULT_ADMIN_PASSWORD: password
